# Generated by Django 4.1.7 on 2023-02-24 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mainimg',
            new_name='mainimage',
        ),
    ]
