# Generated by Django 4.1.7 on 2023-02-26 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0002_rename_mainimg_product_mainimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created']},
        ),
    ]
