# Generated by Django 4.1.7 on 2023-03-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('description', models.CharField(max_length=264)),
                ('body', models.CharField(max_length=264)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('tagList', models.ManyToManyField(to='api.tag')),
            ],
        ),
    ]
